%-------------输入电动机参数----------------
UN=220;PN=22;IaN=115;Nn=1500;K=0.01;
Ra=0.18;%输入电枢电阻
Rf=0.31;%励磁电阻
%-------------------轻载------------------
Ia1=0.5*IaN:(2/3)*IaN;
Ce=(UN-(Ra+Rf)*IaN)/(Nn*K*(2/3)*IaN);%电动势计算常量CeΦn
R=Ra+Rf;
n1=UN./(Ce*K*Ia1)-R/(Ce*K);
Ct=9.55*Ce;
TN1=Ct*K*Ia1.*Ia1;
TNP1=TN1*10;
%-------------------满载------------------
Ia2=(2/3)*IaN:IaN;%电枢电流范围0~IaN
CePhiN=(UN-(Ra+Rf)*IaN)/Nn;%电动势计算常量CeΦn
n=UN/CePhiN-(Ra+Rf)/(CePhiN).*Ia2;%计算转速
CTPhiN=9.55*CePhiN;%电磁转矩常量CtΦn
TN=CTPhiN*Ia2;%计算电磁转矩
TNP=TN*10;%扩大十倍显示
%-------------------画图------------------
plot(Ia1,n1,'b.-',Ia2,n,'b.-',Ia1,TNP1,'r.-',Ia2,TNP,'r.-');%绘制转速特性曲线
xlabel('电枢电流{\itI}_a/A');
ylabel('转速{\itn}/(r/min)，电磁转矩{\itT}/(N.m)');
text(30,1500,'转速{\itn}');%标记转速曲线
text(50,500,'电磁转矩{\itT}(X10)');%标记转矩曲线